import {
  LayoutDashboard,
  Receipt,
  PieChart,
  User,
  Sun,
  Moon,
  Laptop,
  Plus,
  ArrowUpRight,
  ArrowDownLeft,
  Users,
  Wallet,
  Calendar,
  Sparkles,
  Info,
  CheckCircle2,
  AlertCircle,
  Clock,
  Shield,
  ChevronRight,
  TrendingUp,
  CreditCard,
  Building2,
  Home,
  LogOut,
  Settings,
  HelpCircle,
  LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboard,
  expenses: Receipt,
  receipt: Receipt,
  analytics: PieChart,
  profile: User,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  plus: Plus,
  arrowUpRight: ArrowUpRight,
  arrowDownLeft: ArrowDownLeft,
  users: Users,
  wallet: Wallet,
  calendar: Calendar,
  sparkles: Sparkles,
  info: Info,
  checkCircle: CheckCircle2,
  alertCircle: AlertCircle,
  clock: Clock,
  shield: Shield,
  chevronRight: ChevronRight,
  trendingUp: TrendingUp,
  creditCard: CreditCard,
  building: Building2,
  home: Home,
  logout: LogOut,
  settings: Settings,
  help: HelpCircle,
};
