import {
  LayoutDashboard,
  Receipt,
  PieChart,
  User,
  UserPlus,
  Sun,
  Moon,
  Laptop,
  Plus,
  ArrowUpRight,
  ArrowDownLeft,
  Users,
  Wallet,
  Calendar,
  Sparkles,
  Info,
  CheckCircle2,
  AlertCircle,
  Clock,
  Shield,
  ChevronRight,
  TrendingUp,
  CreditCard,
  Building2,
  Home,
  LogOut,
  Settings,
  HelpCircle,
  Check,
  X,
  Pencil,
  RotateCcw,
  ArrowLeft,
  Eye,
  EyeOff,
  Trash2,
  UserX,
  BookOpen,
  Scroll,
  FileText,
  HeartHandshake,
  Search,
  Share2,
  BookmarkCheck,
  Coffee,
  Volume2,
  VolumeX,
  Bike,
  KeyRound,
  Coins,
  UtensilsCrossed,
  Bath,
  Bell,
  ShieldCheck,
  CheckSquare,
  Sparkle,
  Copy,
  LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboard,
  expenses: Receipt,
  receipt: Receipt,
  analytics: PieChart,
  profile: User,
  userPlus: UserPlus,
  userX: UserX,
  trash: Trash2,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  plus: Plus,
  arrowUpRight: ArrowUpRight,
  arrowDownLeft: ArrowDownLeft,
  arrowLeft: ArrowLeft,
  users: Users,
  wallet: Wallet,
  calendar: Calendar,
  sparkles: Sparkles,
  sparkle: Sparkle,
  info: Info,
  checkCircle: CheckCircle2,
  alertCircle: AlertCircle,
  clock: Clock,
  shield: Shield,
  shieldCheck: ShieldCheck,
  shieldAlert: AlertCircle,
  chevronRight: ChevronRight,
  trendingUp: TrendingUp,
  creditCard: CreditCard,
  building: Building2,
  home: Home,
  logout: LogOut,
  settings: Settings,
  help: HelpCircle,
  check: Check,
  x: X,
  close: X,
  edit: Pencil,
  refresh: RotateCcw,
  history: Clock,
  eye: Eye,
  eyeOff: EyeOff,
  rules: BookOpen,
  book: BookOpen,
  scroll: Scroll,
  fileText: FileText,
  handshake: HeartHandshake,
  search: Search,
  share: Share2,
  bookmark: BookmarkCheck,
  coffee: Coffee,
  volume2: Volume2,
  volumeX: VolumeX,
  bike: Bike,
  key: KeyRound,
  coins: Coins,
  utensils: UtensilsCrossed,
  bath: Bath,
  bell: Bell,
  checkSquare: CheckSquare,
  copy: Copy,
};
