import {
  LayoutDashboard,
  Receipt,
  PieChart,
  User,
  UserPlus,
  Sun,
  Moon,
  Laptop,
  Plus,
  ArrowUpRight,
  ArrowDownLeft,
  Users,
  Wallet,
  Calendar,
  Sparkles,
  Info,
  CheckCircle2,
  AlertCircle,
  Clock,
  Shield,
  ChevronRight,
  TrendingUp,
  CreditCard,
  Building2,
  Home,
  LogOut,
  Settings,
  HelpCircle,
  Check,
  X,
  RotateCcw,
  ArrowLeft,
  Eye,
  EyeOff,
  Trash2,
  UserX,
  LucideIcon,
} from "lucide-react";

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboard,
  expenses: Receipt,
  receipt: Receipt,
  analytics: PieChart,
  profile: User,
  userPlus: UserPlus,
  userX: UserX,
  trash: Trash2,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  plus: Plus,
  arrowUpRight: ArrowUpRight,
  arrowDownLeft: ArrowDownLeft,
  arrowLeft: ArrowLeft,
  users: Users,
  wallet: Wallet,
  calendar: Calendar,
  sparkles: Sparkles,
  info: Info,
  checkCircle: CheckCircle2,
  alertCircle: AlertCircle,
  clock: Clock,
  shield: Shield,
  shieldAlert: AlertCircle,
  chevronRight: ChevronRight,
  trendingUp: TrendingUp,
  creditCard: CreditCard,
  building: Building2,
  home: Home,
  logout: LogOut,
  settings: Settings,
  help: HelpCircle,
  check: Check,
  x: X,
  refresh: RotateCcw,
  eye: Eye,
  eyeOff: EyeOff,
};
