import { siteConfig } from "@/config/site";
import { ExpenseWithSplits, UserBalanceSummary } from "@/types/database";

export class WeeklyReportService {
  /**
   * Generate WhatsApp Formatted Weekly Report Markdown String
   */
  static generateWhatsAppWeeklyReport(
    totalExpenses: number,
    roomBalances: UserBalanceSummary[],
    expenses: ExpenseWithSplits[]
  ): string {
    const today = new Date();
    const periodLabel = `Week of ${today.toLocaleDateString("en-US", { month: "short", day: "numeric" })}`;

    // Calculate category totals
    const categoryTotals: Record<string, number> = {};
    expenses.forEach((e) => {
      const cat = e.category || "Grocery";
      categoryTotals[cat] = (categoryTotals[cat] || 0) + Number(e.amount);
    });

    const categoryLines = Object.entries(categoryTotals)
      .map(([cat, amt]) => `• *${cat}*: Rs. ${amt.toLocaleString()}`)
      .join("\n");

    const roommateLines = roomBalances
      .map((b) => {
        const net = b.netBalance;
        if (net > 0) {
          return `🟢 *${b.user.name}*: +Rs. ${net.toLocaleString()} *(Paise LENE HAIN)*`;
        } else if (net < 0) {
          return `🔴 *${b.user.name}*: -Rs. ${Math.abs(net).toLocaleString()} *(Paise DENE HAIN)*`;
        } else {
          return `⚪ *${b.user.name}*: Rs. 0 *(Hisaab Barabar)*`;
        }
      })
      .join("\n");

    return `
=================================
🏠 *${siteConfig.name} - Weekly Khata Report*
📍 *${siteConfig.roomNumber} • ${siteConfig.hostelName}*
📅 _${periodLabel}_
=================================

💵 *Total Room Expenses*: Rs. ${totalExpenses.toLocaleString()}

🛒 *Kharchon Ki Details*:
${categoryLines || "• Abhi koi kharcha nahi hua"}

💰 *Roommates Ka Net Hisaab*:
${roommateLines || "• Sabhi roommates settled hain"}

---------------------------------
📲 *Live Portal Access*: https://kamrakhata.vercel.app
_Report automatically generated by KamraKhata_
=================================
    `.trim();
  }

  /**
   * Launch 1-Click WhatsApp Direct Share
   */
  static shareToWhatsApp(messageText: string, phone?: string): void {
    if (typeof window !== "undefined") {
      const encodedMsg = encodeURIComponent(messageText);
      const url = phone
        ? `https://wa.me/${phone.replace(/[^0-9]/g, "")}?text=${encodedMsg}`
        : `https://wa.me/?text=${encodedMsg}`;

      window.open(url, "_blank");
    }
  }
}
